target-version = "py312"
line-length = 120

exclude = [
    ".git",
    ".venv",
    "node_modules",
    "examples",
    "clarity-agent"
]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "PERF" # perflint
]
ignore = [
    "E501", # line length
    "B008", # FastAPI default parameter function calls
    "B904", # raise ... from err in exception handlers
    "PERF203", # try-except in loop
    "PERF401", # loop extend
    "UP015", # redundant "r" mode argument
]

[lint.per-file-ignores]
"sdk/adversarial_toolio/__init__.py" = ["F401"]
"sdk/tests/*" = ["E402", "F401"]
